// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJkZTqjj8t1AbguIHrK2sNvqVGWy7dLY',
    appId: '1:286209287417:web:4a28bfc1c9a1a2961eae28',
    messagingSenderId: '286209287417',
    projectId: 'appweek4',
    authDomain: 'appweek4.firebaseapp.com',
    storageBucket: 'appweek4.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD93r3OdxXEaXzhsXVqLamLIJm4peaZfTw',
    appId: '1:286209287417:android:e10a69e12d6eed211eae28',
    messagingSenderId: '286209287417',
    projectId: 'appweek4',
    storageBucket: 'appweek4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDooYUJ2h6-2_NWDo-xe8UMjzZGJBBwOZ4',
    appId: '1:286209287417:ios:71aadcd4d9f27a781eae28',
    messagingSenderId: '286209287417',
    projectId: 'appweek4',
    storageBucket: 'appweek4.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDooYUJ2h6-2_NWDo-xe8UMjzZGJBBwOZ4',
    appId: '1:286209287417:ios:71aadcd4d9f27a781eae28',
    messagingSenderId: '286209287417',
    projectId: 'appweek4',
    storageBucket: 'appweek4.appspot.com',
    iosBundleId: 'com.example.complete',
  );

}